#!/usr/bin/env python3
"""Generate C / SystemVerilog / shell / Python / JSON views of the DDR-map profiles.

    spec/gen.py            write spec/generated/
    spec/gen.py --check    exit 1 if spec/generated/ is stale (CI)

Per profile <p> (identifier form P, e.g. GM_FABRIC):
  mister_map_<p>.h    MISTER_<P>_<REGION>_{BASE,SIZE}, MISTER_<P>_<REGION>_<FIELD>_{OFF,PHYS,SIZE},
                      MISTER_<P>_CTRL_<WORD>, MISTER_<P>_ROLE_<ROLE>. When MISTER_PROFILE_<P> is
                      defined, also the unprefixed MISTER_MAP_* aliases.
  mister_map_<p>.vh   `MISTER_<P>_<REGION>_<FIELD>_QW (29-bit qword address = phys >> 3)
  mister_map_<p>.env  MISTER_<P>_*=0x... for busybox devmem / sh
Suite-wide:
  mister_profiles.h   runtime table (profile by name / CORENAME) for probes and libmister
  mister_cores.tsv    CORENAME<TAB>profile, read by device/sh
  mister_mem_wc.env   MISTER_MEM_WC_BASE/SIZE = union allowlist of all profiles
  mister_map.py, mister_map.json
"""
from __future__ import annotations

import argparse
import difflib
import json
import sys
import tempfile
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from mister_spec import Profile, SpecError, load_all, mem_wc_union  # noqa: E402

OUT_DIR = Path(__file__).resolve().parent / "generated"
BANNER = "GENERATED by spec/gen.py from spec/profiles/{src} -- do not edit."


def ident(name: str) -> str:
    return name.upper().replace("-", "_")


def h32(v: int) -> str:
    return f"0x{v:08X}u"


def c_header(p: Profile) -> str:
    P = ident(p.name)
    g = f"MISTER_MAP_{P}_H"
    out = [f"/* {BANNER.format(src=p.path.name)} */", f"/* {p.description} */",
           f"#ifndef {g}", f"#define {g}", ""]
    alias: list[tuple[str, str]] = []

    def d(name: str, val: str, short: str | None = None):
        out.append(f"#define MISTER_{P}_{name:<28} {val}")
        if short:
            alias.append((short, f"MISTER_{P}_{name}"))

    d("FB_DEFAULT_W", str(p.fb_default[0]), "FB_DEFAULT_W")
    d("FB_DEFAULT_H", str(p.fb_default[1]), "FB_DEFAULT_H")
    for r in p.regions.values():
        R = r.name.upper()
        out.append("")
        d(f"{R}_BASE", h32(r.base), f"{R}_BASE")
        d(f"{R}_SIZE", h32(r.size), f"{R}_SIZE")
        for f in r.fields.values():
            d(f"{R}_{f.name}_OFF", h32(f.off), f"{R}_{f.name}_OFF")
            d(f"{R}_{f.name}_PHYS", h32(r.base + f.off), f"{R}_{f.name}_PHYS")
            if f.size:
                d(f"{R}_{f.name}_SIZE", h32(f.size), f"{R}_{f.name}_SIZE")
    if p.ctrl:
        out.append("")
        out.append("/* blitter control block: qword index from the fabric_ctrl role */")
        for w, i in p.ctrl.items():
            d(f"CTRL_{w}", str(i), f"CTRL_{w}")
    if p.mem_wc:
        out.append("")
        d("MEM_WC_BASE", h32(p.mem_wc["base"]), "MEM_WC_BASE")
        d("MEM_WC_SIZE", h32(p.mem_wc["size"]), "MEM_WC_SIZE")
        for i, (lo, hi) in enumerate(p.mem_wc.get("wc_ranges", [])):
            d(f"WC_RANGE{i}_LO", h32(lo), f"WC_RANGE{i}_LO")
            d(f"WC_RANGE{i}_HI", h32(hi), f"WC_RANGE{i}_HI")
        d("WC_RANGE_COUNT", str(len(p.mem_wc.get("wc_ranges", []))), "WC_RANGE_COUNT")
    if p.audio:
        out.append("")
        d("AUDIO_RATE", str(p.audio.get("rate", 0)), "AUDIO_RATE")
        d("AUDIO_CHANNELS", str(p.audio.get("channels", 0)), "AUDIO_CHANNELS")
    out.append("")
    out.append("/* roles: engine-agnostic names -> physical address */")
    for role, phys in p.role_phys().items():
        d(f"ROLE_{role.upper()}", h32(phys), f"ROLE_{role.upper()}")
    out += ["", f"#ifdef MISTER_PROFILE_{P}", f'#define MISTER_MAP_PROFILE_NAME "{p.name}"']
    out += [f"#define MISTER_MAP_{s:<28} {t}" for s, t in alias]
    out += [f"#endif /* MISTER_PROFILE_{P} */", "", f"#endif /* {g} */", ""]
    return "\n".join(out)


def sv_header(p: Profile) -> str:
    P = ident(p.name)
    g = f"MISTER_MAP_{P}_VH"
    out = [f"// {BANNER.format(src=p.path.name)}", "// Addresses are 29-bit DDR3 qword addresses (phys >> 3).",
           f"`ifndef {g}", f"`define {g}", ""]
    out.append(f"`define MISTER_{P}_FB_DEFAULT_W {p.fb_default[0]}")
    out.append(f"`define MISTER_{P}_FB_DEFAULT_H {p.fb_default[1]}")
    for r in p.regions.values():
        R = r.name.upper()
        out.append(f"`define MISTER_{P}_{R}_BASE_QW 29'h{r.base >> 3:07X}")
        for f in r.fields.values():
            phys = r.base + f.off
            if phys % 8:
                out.append(f"// {R}_{f.name} (0x{phys:08X}) is not qword-aligned; byte address only")
                out.append(f"`define MISTER_{P}_{R}_{f.name}_PHYS 32'h{phys:08X}")
                continue
            out.append(f"`define MISTER_{P}_{R}_{f.name}_QW 29'h{phys >> 3:07X}  // 0x{phys:08X}")
    for w, i in p.ctrl.items():
        out.append(f"`define MISTER_{P}_CTRL_{w} 29'd{i}")
    out += ["", f"`endif // {g}", ""]
    return "\n".join(out)


def env_file(p: Profile) -> str:
    P = ident(p.name)
    out = [f"# {BANNER.format(src=p.path.name)}", f"# POSIX sh; source it. Physical byte addresses for busybox devmem.",
           f"MISTER_{P}_PROFILE={p.name}"]
    for r in p.regions.values():
        R = r.name.upper()
        out.append(f"MISTER_{P}_{R}_BASE=0x{r.base:08X}")
        out.append(f"MISTER_{P}_{R}_SIZE=0x{r.size:08X}")
        for f in r.fields.values():
            out.append(f"MISTER_{P}_{R}_{f.name}=0x{r.base + f.off:08X}")
    if p.ctrl and "fabric_ctrl" in p.roles:
        cb = p.resolve(p.roles["fabric_ctrl"])
        for w, i in p.ctrl.items():
            out.append(f"MISTER_{P}_{w}=0x{cb + 8 * i:08X}")
    if p.mem_wc:
        out.append(f"MISTER_{P}_MEM_WC_BASE=0x{p.mem_wc['base']:08X}")
        out.append(f"MISTER_{P}_MEM_WC_SIZE=0x{p.mem_wc['size']:08X}")
    for role, phys in p.role_phys().items():
        out.append(f"MISTER_{P}_ROLE_{role.upper()}=0x{phys:08X}")
    return "\n".join(out) + "\n"


ROLE_ORDER = ["video_ctrl", "fb_buf0", "fb_buf1", "joy_p1", "joy_p2", "joy_p3", "joy_p4",
              "audio_wr", "audio_rd", "audio_ring", "scanout_counter", "fabric_ctrl"]


def profiles_header(profiles: dict[str, Profile]) -> str:
    unknown = {r for p in profiles.values() for r in p.roles} - set(ROLE_ORDER)
    if unknown:
        raise SpecError(f"roles not in gen.py ROLE_ORDER: {sorted(unknown)}")
    out = [f"/* {BANNER.format(src='(all)')} */",
           "/* Runtime profile table: pick a profile by name or by /tmp/CORENAME. */",
           "#ifndef MISTER_PROFILES_H", "#define MISTER_PROFILES_H", "", "#include <stdint.h>", "",
           "typedef enum {"]
    out += [f"    MISTER_ROLE_{r.upper()}," for r in ROLE_ORDER]
    out += ["    MISTER_ROLE__COUNT", "} mister_role_t;", "",
            "typedef struct {",
            "    const char *name;",
            "    const char *const *cores;      /* NULL-terminated CORENAME list */",
            "    uint16_t fb_default_w, fb_default_h;",
            "    uint32_t mem_wc_base, mem_wc_size;",
            "    uint32_t wc_ranges[4][2];      /* [lo, hi) physical; wc_range_count used */",
            "    uint32_t wc_range_count;",
            "    uint32_t role[MISTER_ROLE__COUNT]; /* physical address, 0 = absent */",
            "} mister_profile_t;", ""]
    for p in profiles.values():
        P = ident(p.name).lower()
        cores = ", ".join(f'"{c}"' for c in p.cores)
        out.append(f"static const char *const mister_cores_{P}[] = {{ {cores}{', ' if cores else ''}0 }};")
    out += ["", "static const mister_profile_t mister_profiles[] = {"]
    for p in profiles.values():
        P = ident(p.name).lower()
        phys = p.role_phys()
        wc = p.mem_wc or {}
        ranges = wc.get("wc_ranges", [])
        if len(ranges) > 4:
            raise SpecError(f"{p.name}: more than 4 wc_ranges")
        rng = ", ".join(f"{{{h32(lo)}, {h32(hi)}}}" for lo, hi in ranges) or "{0, 0}"
        roles = ", ".join(h32(phys.get(r, 0)) for r in ROLE_ORDER)
        out += ["    {",
                f'        "{p.name}", mister_cores_{P}, {p.fb_default[0]}, {p.fb_default[1]},',
                f"        {h32(wc.get('base', 0))}, {h32(wc.get('size', 0))},",
                f"        {{ {rng} }}, {len(ranges)},",
                f"        {{ {roles} }},",
                "    },"]
    out += ["};", f"#define MISTER_PROFILE_COUNT {len(profiles)}", "", "#endif /* MISTER_PROFILES_H */", ""]
    return "\n".join(out)


def py_json(profiles: dict[str, Profile]) -> dict:
    data = {}
    for p in profiles.values():
        data[p.name] = {
            "description": p.description,
            "cores": p.cores,
            "fb_default": list(p.fb_default),
            "regions": {r.name: {"base": r.base, "size": r.size,
                                 "fields": {f.name: {"off": f.off, "phys": r.base + f.off, "size": f.size}
                                            for f in r.fields.values()}}
                        for r in p.regions.values()},
            "ctrl": p.ctrl,
            "mem_wc": p.mem_wc,
            "audio": p.audio,
            "roles": p.role_phys(),
        }
    return data


def render(profiles: dict[str, Profile]) -> dict[str, str]:
    files: dict[str, str] = {}
    for p in profiles.values():
        files[f"mister_map_{p.name.replace('-', '_')}.h"] = c_header(p)
        files[f"mister_map_{p.name.replace('-', '_')}.vh"] = sv_header(p)
        files[f"mister_map_{p.name.replace('-', '_')}.env"] = env_file(p)
    files["mister_profiles.h"] = profiles_header(profiles)
    files["mister_cores.tsv"] = "".join(f"{c}\t{p.name}\n" for p in profiles.values() for c in p.cores)
    base, size = mem_wc_union(profiles)
    files["mister_mem_wc.env"] = (f"# {BANNER.format(src='(all)')}\n"
                                  f"# Union of every profile's mem_wc window; the loader inserts mem_wc once with this.\n"
                                  f"MISTER_MEM_WC_BASE=0x{base:08X}\nMISTER_MEM_WC_SIZE=0x{size:08X}\n")
    data = py_json(profiles)
    files["mister_map.json"] = json.dumps(data, indent=1, sort_keys=True) + "\n"
    files["mister_map.py"] = (f"# {BANNER.format(src='(all)')}\n"
                              f"PROFILES = {json.dumps(data, indent=1, sort_keys=True)}\n"
                              f"CORES = {json.dumps({c: p.name for p in profiles.values() for c in p.cores}, sort_keys=True)}\n"
                              f"MEM_WC_UNION = (0x{base:08X}, 0x{size:08X})\n")
    return files


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true", help="fail if spec/generated is stale")
    ap.add_argument("--out", type=Path, default=OUT_DIR)
    a = ap.parse_args()
    try:
        files = render(load_all())
    except SpecError as e:
        print(f"spec error: {e}", file=sys.stderr)
        return 2
    if a.check:
        stale = []
        present = {p.name for p in a.out.glob("*")} if a.out.is_dir() else set()
        for name, text in files.items():
            cur = (a.out / name).read_text() if (a.out / name).exists() else ""
            if cur != text:
                stale.append(name)
                sys.stdout.writelines(difflib.unified_diff(cur.splitlines(True), text.splitlines(True),
                                                           f"committed/{name}", f"generated/{name}", n=1))
        extra = present - set(files)
        for name in sorted(extra):
            stale.append(name)
            print(f"stale extra file: {name}")
        if stale:
            print(f"\nspec/generated is stale ({len(stale)} file(s)); run spec/gen.py", file=sys.stderr)
            return 1
        print(f"spec/generated up to date ({len(files)} files)")
        return 0
    a.out.mkdir(parents=True, exist_ok=True)
    for old in a.out.glob("*"):
        if old.name not in files:
            old.unlink()
    for name, text in files.items():
        (a.out / name).write_text(text)
    print(f"wrote {len(files)} files to {a.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
